### ISSUE TITLE
Yandex Music

### ISSUE THREAD

**Issue by papados** [threethan/QuestAudioPatcher#9]
Hello, yandex music app (https://play.google.com/store/apps/details?id=ru.yandex.music&hl=en) patched wrong. After patch, app install error. 
Quest 3, not patched app works ok. 

QSideloader.Exceptions.AdbServiceException: Failed to sideload game
 --- AdvancedSharpAdbClient.DeviceCommands.PackageInstallationException: INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed parse during installPackageLI: Failed to read manifest from /data/app/vmdl282587823.tmp/base.apk: length522; index-1
   at AdvancedSharpAdbClient.DeviceCommands.PackageManager.InstallRemotePackage(String remoteFilePath, Boolean reinstall, Boolean grantRuntimePermissions)
   at AdvancedSharpAdbClient.DeviceCommands.PackageManager.InstallPackage(String packageFilePath, Boolean reinstall, Boolean grantRuntimePermissions, CancellationToken ct)
   at QSideloader.Services.AdbService.AdbDevice.InstallPackage(String apkPath, Boolean reinstall, Boolean grantRuntimePermissions, IProgress1 progress, CancellationToken ct) in D:\a\QLoader\QLoader\QSideloader\Services\AdbService.cs:line 1751
   at QSideloader.Services.AdbService.AdbDevice.c__DisplayClass71_0.SideloadGameg__InstallApk1(IObserver1 observer, String apkPath) in D:\a\QLoader\QLoader\QSideloader\Services\AdbService.cs:line 1516
   at QSideloader.Services.AdbService.AdbDevice.c__DisplayClass71_0.SideloadGameb__0(IObserver1 observer) in D:\a\QLoader\QLoader\QSideloader\Services\AdbService.cs:line 1416
   --- End of inner exception stack trace ---

App Version: v1.0.3-dev
OS: Windows Microsoft Windows NT 10.0.19045.0

patched apk https://dropmefiles.com/tAqQ8

**Comment by Jangberry** [comment]
Got the same issue with Spotify on Quest 2:

I tried to patch Spotify v8.8.76.667, that I get to work ok too (like I get to log in and play music, it just won't work in background).
But the output apk won't install: *`an issue happend while analysing this package`*

I tried to install it with adb to get a bit more details, and I got this error:
```
$ adb install com.spotify.music_aee-signed.apk 
Performing Streamed Install
adb: failed to install com.spotify.music_aee-signed.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed parse during installPackageLI: Failed to read manifest from /data/app/vmdl1193505662.tmp/base.apk: length=631; index=-1]
```

The manifest in the output apk looks weird with a lot of non-printable or even null characters

Hope this might help to solve this issue !
